/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValuationRouteImport } from './routes/valuation'
import { Route as SellRouteImport } from './routes/sell'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as BuyersRouteImport } from './routes/buyers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as DashboardIdRouteImport } from './routes/dashboard.$id'

const ValuationRoute = ValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersRoute = BuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIdRoute = DashboardIdRouteImport.update({
  id: '/dashboard/$id',
  path: '/dashboard/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buyers': typeof BuyersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/marketplace': typeof MarketplaceRoute
  '/sell': typeof SellRoute
  '/valuation': typeof ValuationRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buyers': typeof BuyersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/marketplace': typeof MarketplaceRoute
  '/sell': typeof SellRoute
  '/valuation': typeof ValuationRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buyers': typeof BuyersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/marketplace': typeof MarketplaceRoute
  '/sell': typeof SellRoute
  '/valuation': typeof ValuationRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/listing/$id': typeof ListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buyers'
    | '/how-it-works'
    | '/marketplace'
    | '/sell'
    | '/valuation'
    | '/dashboard/$id'
    | '/listing/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buyers'
    | '/how-it-works'
    | '/marketplace'
    | '/sell'
    | '/valuation'
    | '/dashboard/$id'
    | '/listing/$id'
  id:
    | '__root__'
    | '/'
    | '/buyers'
    | '/how-it-works'
    | '/marketplace'
    | '/sell'
    | '/valuation'
    | '/dashboard/$id'
    | '/listing/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyersRoute: typeof BuyersRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MarketplaceRoute: typeof MarketplaceRoute
  SellRoute: typeof SellRoute
  ValuationRoute: typeof ValuationRoute
  DashboardIdRoute: typeof DashboardIdRoute
  ListingIdRoute: typeof ListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/valuation': {
      id: '/valuation'
      path: '/valuation'
      fullPath: '/valuation'
      preLoaderRoute: typeof ValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers': {
      id: '/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof BuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$id': {
      id: '/dashboard/$id'
      path: '/dashboard/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof DashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyersRoute: BuyersRoute,
  HowItWorksRoute: HowItWorksRoute,
  MarketplaceRoute: MarketplaceRoute,
  SellRoute: SellRoute,
  ValuationRoute: ValuationRoute,
  DashboardIdRoute: DashboardIdRoute,
  ListingIdRoute: ListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
